# EKS Staging 클러스터 Istio 설정

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

  # Sidecar Proxy 기본 리소스 설정
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

  meshConfig:
    accessLogFile: /dev/stdout
