{{- if .Values.metrics.enabled }}
---
# ArgoCD Server Metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: argocd
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  namespaceSelector:
    matchNames:
      - argocd
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
# ArgoCD Application Controller Metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-application-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: argocd
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  namespaceSelector:
    matchNames:
      - argocd
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
# ArgoCD Repo Server Metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-repo-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: argocd
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  namespaceSelector:
    matchNames:
      - argocd
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
{{- end }}
