apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/namespaces.yaml
  # TODO: EKS prod 인프라 추가 예정
  # - infra/eso.yaml
  # - infra/rbac.yaml
  # - infra/argocd.yaml
  # - infra/istio.yaml
  # - infra/monitoring.yaml
  # - prod.yaml
